---
# Modules Used

# https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
# https://docs.ansible.com/ansible/latest/modules/bigip_wait_module.html
# https://docs.ansible.com/ansible/latest/modules/uri_module.html
# https://docs.ansible.com/ansible/latest/modules/template_module.html
# https://docs.ansible.com/ansible/latest/modules/get_url_module.html


# Ansible Information
- name: Set Ansible Information
  hosts: localhost
  gather_facts: False
  connection: local
  vars:
    BIGIPadminUsername: ""
    BIGIPadminPassword: ""
    deviceName: ""

# Deploy DO Declarations
  tasks:
    - name: Wait a maximum of 300 seconds for BIG-IP to be ready to take configuration
      bigip_wait:
        timeout: 300
        provider:
          password: "{{ BIGIPadminPassword }}"
          server: "{{ deviceName }}"
          user: "{{ BIGIPadminUsername }}"
          validate_certs: no

    - name: Get BIG-IP Authentication Token from {{ deviceName }}
      uri:
        body: '{"username":"{{ BIGIPadminUsername }}","password":"{{ BIGIPadminPassword }}","loginProviderName":"tmos"}'
        body_format: json
        method: POST
        url: "https://{{ deviceName }}/mgmt/shared/authn/login"
        status_code: "200"
        validate_certs: no
      register: bigip1_auth_response
      retries: 30
      delay: 5
      until: "(bigip1_auth_response is successful) and (bigip1_auth_response.status == 200)"

    - name: Assign Auth Token to Variable
      set_fact:
        bigip1_auth_token: "{{ bigip1_auth_response.json.token.token }}"

    - name: Prepare the DO declaration
      template: src="~/AWS_Quick_Start/templates/declarative-onboarding.template" dest="~/AWS_Quick_Start/templates/{{ deviceName }}_declaration.j2"
      delegate_to: localhost

    - name: Validate {{ deviceName }} DO Rest Worker is ready
      uri:
        headers:
          X-F5-Auth-Token: "{{ bigip1_auth_token }}"
        method: GET
        url: "https://{{ deviceName }}/mgmt/shared/declarative-onboarding/available"
        validate_certs: no
      retries: 30
      delay: 5
      register: result
      until: "(result is successful) and (result.status == 200)"

    - name: Create or update {{ deviceName }}; DO Declaration
      uri:
        body: "{{ lookup('file','~/AWS_Quick_Start/templates/' + '{{ deviceName }}_declaration.j2') }}"
        body_format: json
        headers:
          X-F5-Auth-Token: "{{ bigip1_auth_token }}"
        method: POST
        status_code: "202"
        url: "https://{{ deviceName }}/mgmt/shared/declarative-onboarding"
        validate_certs: no
        timeout: "60"

    - name: Delete BIG-IP Authentication Token from {{deviceName}}
      uri:
        headers:
          X-F5-Auth-Token: "{{ bigip1_auth_token }}"
        method: DELETE
        url: "https://{{ deviceName }}/mgmt/shared/authz/tokens/{{ bigip1_auth_token }}"
        status_code: "200"
        validate_certs: no
      register: bigip1_token_delete
      retries: 30
      delay: 5
      until: "(bigip1_token_delete is successful) and (bigip1_token_delete.status == 200)"